Repository openshift/cluster-baremetal-operator, pull requests merged in 2020-12, with the labels that each got.

#81 Bug 1901301: Handle case when Provisioning CR is absent on BareMetal Platform
  controllers/clusteroperator.go
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-urgent, lgtm

#73 Use hostIP for ironic containers when provisionig network disabled
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: approved, lgtm

#72 Enable Deployment updates
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
Labels: approved, lgtm

#78 Annotate manifests for single-node-developer cluster profile
  config/profiles/default/kustomization.yaml
  controllers/bindata.go
  controllers/clusteroperator_test.go
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
  manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
Labels: approved, lgtm

#83 The bmh relatedobject name should be an empty string.
  controllers/clusteroperator.go
Labels: approved, lgtm

#82 baremetal_pod: add log watcher containers
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: approved, lgtm

#77 Turn on auth for ironic json-rpc
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_secrets.go
  provisioning/baremetal_secrets_test.go
Labels: approved, lgtm

#76 Add a second-level image cache
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
  provisioning/provisioning_info.go
  provisioning/state_service.go
Labels: approved, lgtm

#85 Bug 1903717: Change default Deployment selector and handle downgrades
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#86 Set IPA URLs using API VIP
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
Labels: approved, lgtm

#88 Bug 1905307: cluster-baremetal-operator: add provisioning CR as related object
  controllers/clusteroperator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#89 Bug 1866901: Don't do rolling updates of metal3 Deployment
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#65 Bug 1906105: Annotate existing metal3 deployment
  controllers/clusteroperator.go
  controllers/clusteroperator_test.go
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#71 Bug 1906935: Delete resources when Provisioning CR is deleted
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_secrets.go
  provisioning/baremetal_secrets_test.go
  provisioning/image_cache.go
  provisioning/state_service.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
