Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-04, with the labels that each got.

#125 Bug 1948787: secret.StringData is a WriteOnly convience field, stop using it to read
  provisioning/baremetal_crypto.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_secrets.go
  provisioning/baremetal_secrets_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#124 Add management workload annotations
  config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
  config/profiles/default/manager_auth_proxy_patch.yaml
  config/profiles/default/manager_webhook_patch.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
Labels: approved, bugzilla/valid-bug, lgtm

#126 Bug 1903700: Fix Pod Selectors in metal3 pods created by CBO
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#131 Bug 1952667: Update Readme with detailed information about the CBO
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#130 Rename workload annotations
  config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
  config/profiles/default/manager_auth_proxy_patch.yaml
  config/profiles/default/manager_webhook_patch.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/valid-bug, lgtm
