Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-09, with the labels that each got.

#196 Remove ironic-inspector reference in CBO
  manifests/image-references
  provisioning/sample_images.json
Labels: lgtm, approved

#166 Bug 1975711: Only start static ip set if provisioning net not disabled
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, approved

#195 Bug 2000081: add a new field "ProvisioningMacAddresses" to the provisioning CRD
  api/v1alpha1/provisioning_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_provisionings.yaml
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#191 Bug 1991641: make provisioning CR status more explicit and remove the ownership on the CO
  controllers/clusteroperator.go
  controllers/clusteroperator_test.go
  controllers/provisioning_controller.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#194 Bug 2000445: Set LIVE_ISO_FORCE_PERSISTENT_BOOT_DEVICE=Never
  provisioning/baremetal_pod.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-urgent, approved

#201 generate the ProvisioningSpec help in the README
  README.md
  api/v1alpha1/provisioning_types.go
  hack/readme_inputs/main.go
Labels: lgtm, approved

#202 Set IRONIC_AGENT_IMAGE in the ipa init container
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/image-references
  provisioning/baremetal_pod.go
  provisioning/container_images.go
Labels: lgtm, approved

#204 Add the Ironic Agent image to the list of sample images
  provisioning/sample_images.json
Labels: lgtm, approved

#200 Bug 2004597: Remove duplicate ramdisk log container
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-low, lgtm, approved
