Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-02, with the labels that each got.

#98 bug 1906143: Use k8s.io/klog instead of zap
  controllers/clusteroperator.go
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
  go.mod
  main.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#100 Update bmh crd
  hack/get-bmh-crd.sh
  manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
Labels: approved, lgtm

#105 Update BMH CRD from metal3-io/baremetal-operator
  hack/get-bmh-crd.sh
  manifests/0000_31_cluster-baremetal-operator_03_baremetalhost.crd.yaml
Labels: approved, lgtm

#107 Add POD_NAMESPACE env variable to bmo container
  provisioning/baremetal_pod.go
Labels: approved, lgtm

#104 Bug 1927068: provisioning: configure DHCP range with netmask
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#110 Fix annotations for the prometheus manifests
  config/prometheus/kustomization.yaml
  manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
  manifests/0000_90_cluster-baremetal-operator_04_alertrules.yaml
Labels: approved, lgtm

#111 Remove the CBO down alert
  Makefile
  config/prometheus/alertrules.yaml
  config/prometheus/kustomization.yaml
  manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
  manifests/0000_90_cluster-baremetal-operator_04_alertrules.yaml
Labels: approved, lgtm

#108 Add a couple more linters and fix some issues raised
  .golangci.yml
  controllers/provisioning_controller.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/baremetal_secrets_test.go
  provisioning/container_images_test.go
Labels: approved, lgtm

#106 Allow BMO to watch all Namespaces
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
Labels: approved, lgtm
