Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-01, with the labels that each got.

#91 Bug 1913716: Use existing libraries instead of rolling our own
  controllers/clusteroperator.go
  controllers/clusteroperator_test.go
  controllers/provisioning_controller.go
  go.mod
  go.sum
  provisioning/baremetal_pod.go
  provisioning/baremetal_secrets.go
  provisioning/container_images.go
  provisioning/image_cache.go
  provisioning/state_service.go
  vendor/github.com/stretchr/stew/slice/README.md
  vendor/github.com/stretchr/stew/slice/common.go
  vendor/github.com/stretchr/stew/slice/contains.go
  vendor/github.com/stretchr/stew/slice/doc.go
  vendor/github.com/stretchr/stew/slice/minus.go
  vendor/github.com/stretchr/stew/slice/plus.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#93 Bug 1909527: Update Labels on the Pod TemplateSpec of the metal3 Deployment
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#95 Bug 1915959: Add missing exclude annotations for hosted control plane
  controllers/bindata.go
  controllers/clusteroperator_test.go
  manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
  manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#92 Bug 1913047: Remove intermediate CO progressing state
  controllers/provisioning_controller.go
  provisioning/baremetal_pod.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#96 Bug 1900322: Add Toleration OP Exists to metal3 pod
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
