Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-06, with the labels that each got.

#121 Bug 1940518: Set default resource requests for all containers
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#148 Bug 1946079: pass IP_OPTIONS env down to the OS downloader container
  controllers/provisioning_controller.go
  provisioning/baremetal_config.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/image_cache.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#151 Bug 1946079: Fix parsing of IPv6 APIserver IP address
  controllers/provisioning_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#153 Bug 1968615: Restrict watches to openshift-machine-api
  main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#156 Bug 1968701: Add ironic/inspector TlsMounts to baremetal pod
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#158 Bug 1946079: Fix network stack calculation
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#163 Don't set IP options on kernel command line twice
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
Labels: approved, lgtm

#159 Use new registry registry.ci.openshift.org
  config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
  config/profiles/default/manager_auth_proxy_patch.yaml
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  manifests/image-references
  provisioning/container_images_test.go
  provisioning/sample_images.json
Labels: approved, lgtm

#165 Bug 1972753: Only start static ip set if provisioning net not disabled
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#144 Allow boot iso source configuration
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  provisioning/baremetal_config.go
Labels: approved, lgtm

#150 Add VirtualMediaViaExternalNetwork flag to the Provisioning CRD
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
Labels: approved, lgtm

#137 Update controller-runtime version to v0.8.3
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/client_builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/client_builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/inject/inject.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/response.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
Labels: approved, lgtm

#115 Bug 1961226: Configure an IPA sshkey in the metal3 pod
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#170 remove dhellmann from owners
  OWNERS
Labels: approved, lgtm

#169 Bug 1973724: reorder the initContainers, so that static-ip-set happens prior to the image download
  provisioning/baremetal_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
