Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-11, with the labels that each got.

#213 Change BMO validatingwebhook port to 9447
  provisioning/baremetal_config.go
  provisioning/baremetal_webhook_test.go
Labels: lgtm, approved

#206 Serve virtual media ISOs over TLS
  README.md
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  provisioning/baremetal_config.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/state_service.go
Labels: lgtm, approved

#214 Bug 1991641: Fix CO message when Provisioning CR is not present
  controllers/clusteroperator.go
  controllers/provisioning_controller.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#217 Bug 2024900: Not enable CBO webhook in unsupported platform
  controllers/provisioning_controller.go
  main.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved

#218 Remove stbenjam from OWNERS
  OWNERS
Labels: lgtm, approved

#216 Bug 2023604: Allow validatingwebhookconfigurations to delete Provisioning CR
  api/v1alpha1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Labels: lgtm, approved
