Repository openshift/cluster-baremetal-operator, pull requests merged in 2021-07, with the labels that each got.

#132 Use ironic image for ironic-inspector
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/container_images.go
  provisioning/container_images_test.go
Labels: approved, lgtm

#164 Bug: 1947293 Add managed provisioning network size validation
  api/v1alpha1/provisioning_types.go
  api/v1alpha1/provisioning_validation.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
Labels: approved, lgtm

#167 Add quick network info for boot iso image source option
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
Labels: approved, lgtm

#161 [release-4.7] Bug 1972291: Use a cache URL with the .svc.cluster.local suffix
  provisioning/image_cache.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#172 Pass IRONIC_EXTERNAL_IP to Ironic container
  provisioning/baremetal_pod.go
Labels: approved, lgtm

#176 Set external IP env var for ironic conductor too.
  provisioning/baremetal_pod.go
Labels: approved, lgtm

#180 Customize metal3 health endpoint to avoid port conflicts
  provisioning/baremetal_pod.go
Labels: approved, lgtm

#174 Add support for live images and configuration of coreos IPA
  api/v1alpha1/provisioning_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  provisioning/baremetal_config.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_secrets.go
  provisioning/image_cache.go
Labels: approved, lgtm

#182 Bug 1984576: Rebase of pull/177 (Pass MACs to set-static-ip initContainer) + unit tests
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#184 Bug 1986464: Send pull secret data as base64 encoded string
  provisioning/baremetal_secrets.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#171 [release-4.7] Bug 1973367: Pass IP_OPTIONS=dhcp|dhcp6 down to OS Downloader container
  controllers/provisioning_controller.go
  provisioning/baremetal_config.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/image_cache.go
  provisioning/provisioning_info.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#185 Bug 1986462: Separate the names of machine os downloader when two copies are started
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
