Repository openshift/cluster-baremetal-operator, pull requests merged in 2022-01, with the labels that each got.

#230 Bug 2034527: Base IPA kernel params on provisioning network IP version
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved

#229 Bug 2038088: Remove references to ipa-downloader
  api/v1alpha1/zz_generated.deepcopy.go
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/image-references
  provisioning/baremetal_pod_test.go
  provisioning/container_images.go
  provisioning/container_images_test.go
  provisioning/sample_images.json
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#231 Bug 2038272: Create image-customization-controller when metal3 Pod not up
  provisioning/baremetal_pod.go
  provisioning/image_customization.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#227 Bug 2037483: Allow CBO to list Pods only in the openshift-machine-api namespace
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#232 Bug 2038196: Add new resources to relatedObjects
  controllers/clusteroperator.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved

#233 Bug 2034527: Pass IP options to installed CoreOS image
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/image_customization.go
  provisioning/machine_os_images.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved

#235 Bug 2040710: Pluralize BMC subscription CR name in RBAC
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved

#237 Bug 2041510: Enable webhook for bmceventsubscriptions
  provisioning/baremetal_webhook.go
  provisioning/baremetal_webhook_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved

#239 Bug 2040671: Fix the way the network stack is determined
  api/v1alpha1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
  go.mod
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent, approved

#240 Bug 2045927: Add proxy for image-customization-controller
  provisioning/image_customization.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved, ok-to-test

#228 Remove asalkeld and kirankt from Owners
  OWNERS
Labels: lgtm, approved
