Repository openshift/cluster-baremetal-operator, pull requests merged in 2022-06, with the labels that each got.

#268 [release-4.9] Bug 2091747: Fix interpretation of Deployment Status Conditions
  provisioning/baremetal_pod.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-urgent, approved, backport-risk-assessed

#243 Bug 2099928: Add UT for image_customization_test
  provisioning/image_customization_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium, approved, ok-to-test

#272 Bug 2084215: Add baremetal prefix to kube-rbac-proxy
  Makefile
  config/profiles/default/manager_auth_proxy_patch.yaml
  config/prometheus/proxyconfig.yaml
  manifests/0000_31_cluster-baremetal-operator_05_baremetal-kube-rbac-proxy-config.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high, approved
