Repository openshift/cluster-baremetal-operator, pull requests merged in 2022-09, with the labels that each got.

#285 Added handling PlatformStatus.Type other than Baremetal
  controllers/provisioning_enabled.go
  provisioning/utils.go
Labels: lgtm, approved

#284 OCPBUGS-651: ignore metal3 pods that are terminating
  provisioning/utils.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important

#283 OCPBUGS-747: do not rely on string "master" to be in BMH names
  config/rbac/role.yaml
  controllers/provisioning_controller.go
  controllers/provisioning_controller_test.go
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important

#296 Update with current OWNERS
  OWNERS
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed

#297 Update with current OWNERS
  OWNERS
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed

#288 Pass IRONIC_EXTERNAL_URL_V6 to baremetal-operator
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: lgtm, approved
