Repository openshift/cluster-baremetal-operator, pull requests merged in 2022-12, with the labels that each got.

#313 OCPBUGS-4689: Do not fail the reconciler when no master Machines exist
  controllers/provisioning_controller.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/severity-moderate, jira/valid-bug

#310 Ensure we set ipv6 url in external url var
  controllers/bindata.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/utils.go
Labels: lgtm, approved

#303 OCPBUGS-1844: enable DNS in the provisioning dnsmasq
  README.md
  api/v1alpha1/provisioning_types.go
  config/crd/bases/metal3.io_provisionings.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important

#315 OCPBUGS-4712: delete ironic-proxy/image-cache when not needed
  controllers/provisioning_controller.go
  provisioning/image_cache.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/severity-moderate, jira/valid-bug
