Repository openshift/cluster-baremetal-operator, pull requests merged in 2023-04, with the labels that each got.

#324 OCPBUGS-4248: Set external Ironic URL to ironic-proxy IP
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
  provisioning/ironic_proxy.go
  provisioning/utils.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#335 Revert "proxy: pass ipv6 address to container"
  provisioning/ironic_proxy.go
Labels: lgtm, approved

#333 OCPBUGS-10343: use proxying for inspector in addition to ironic
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
  provisioning/ironic_proxy.go
  provisioning/utils.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/valid-reference

#334 Use a file URL for passing kernel to Ironic
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod_test.go
Labels: lgtm, approved

#338 [release-4.13] OCPBUGS-11985: use proxying for inspector in addition to ironic
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/ironic_proxy.go
  provisioning/utils.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
