Repository openshift/cluster-baremetal-operator, pull requests merged in 2023-11, with the labels that each got.

#374 OCPBUGS-20563: Add tls-cipher-suites to baremetal-kube-rbac-proxy
  config/profiles/default/manager_auth_proxy_patch.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#343 NO-ISSUE: Stop linting when building the image
  Dockerfile
  Makefile
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#380 OCPBUGS-23131,OCPBUGS-23149: fix IRONIC_EXTERNAL_URL_V6
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/bmo_pod_test.go
  provisioning/image_customization.go
  provisioning/ironic_proxy.go
  provisioning/utils.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#391 OCPBUGS-23504: hack for deploying V6-only clusters from dualstack hubs
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#389 OCPBUGS-23291: hack for deploying V6-only clusters from dualstack hubs
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
