Repository openshift/cluster-baremetal-operator, pull requests merged in 2024-02, with the labels that each got.

#396 OCPBUGS-27145: Reduce container privileges
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
  provisioning/image_customization.go
  provisioning/ironic_proxy.go
  provisioning/machine_os_images.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#400 OCPBUGS-24579: pass all IPs to image-customization-controller
  provisioning/baremetal_pod.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#403 OCPBUGS-27760: Update the leader election durations to be tolerant
  main.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
