Repository openshift/cluster-baremetal-operator, pull requests merged in 2024-07, with the labels that each got.

#407 AUTH-482: set required-scc for openshift workloads
  config/cluster-baremetal-operator/cluster-baremetal-operator.yaml
  config/profiles/default/manager_auth_proxy_patch.yaml
  config/profiles/default/manager_webhook_patch.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#408 OCPBUGS-29687: Move Secrets from environment variables to VolumeMounts in metal3-httpd container
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#430 METAL-503: Remove ironic-inspector
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
  provisioning/baremetal_secrets.go
  provisioning/baremetal_secrets_test.go
  provisioning/bmo_pod.go
  provisioning/bmo_pod_test.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
  provisioning/ironic_proxy.go
  provisioning/state_service.go
  provisioning/utils.go
Labels: lgtm, approved, jira/valid-reference

#423 METAL-1040: Allow CBO to run without MAPI
  controllers/provisioning_controller.go
Labels: lgtm, approved, jira/valid-reference

#434 OCPBUGS-36285: Mount htpasswds as volumeMounts in metal3-httpd container
  provisioning/baremetal_pod.go
  provisioning/baremetal_pod_test.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#429 OCPBUGS-29660: Ignore provisioning ip config if disabled
  provisioning/baremetal_config.go
  provisioning/baremetal_pod_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#436 OCPBUGS-36285: Move pull secret from env var to VolumeMount in metal3-image-customization container
  provisioning/baremetal_pod.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
