Repository openshift/cluster-baremetal-operator, pull requests merged in 2024-05, with the labels that each got.

#415 OCPBUGS-33254: Wait for bootstrapping to finish before starting
  controllers/provisioning_controller.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#401 OCPBUGS-27145: Drop unneccessary capabilities
  provisioning/baremetal_pod.go
  provisioning/image_cache.go
  provisioning/image_customization.go
  provisioning/ironic_proxy.go
  provisioning/machine_os_images.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#416 OCPBUGS-33493: Enable leader election for baremetal-operator
  provisioning/bmo_pod.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#417 OCPBUGS-32304: Run metal3 containers as specific users and groups
  provisioning/baremetal_pod.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only
