Repository openshift/cluster-baremetal-operator, pull requests merged in 2024-06, with the labels that each got.

#418 OCPBUGS-34041: Run metal3 containers as specific users and groups
  provisioning/baremetal_pod.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#422 OCPBUGS-34649: provisioning: add ownership for tls secret
  provisioning/baremetal_secrets.go
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#424 OCPBUGS-35211: Add capability to metal3-ramdisk-logs container
  provisioning/baremetal_pod.go
Labels: lgtm, approved, qe-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#426 OCPBUGS-35503: Add capability to metal3-ramdisk-logs container
  provisioning/baremetal_pod.go
Labels: cherry-pick-approved, lgtm, approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#428 OCPBUGS-29687: Move pull secret from env var to VolumeMount in metal3-image-customization container
  provisioning/baremetal_pod.go
  provisioning/image_customization.go
  provisioning/image_customization_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
