Repository openshift/cluster-baremetal-operator, pull requests merged in 2025-06, with the labels that each got.

#482 OCPBUGS-56723: Treat ResourceNotFound as non-fatal
  controllers/clusteroperator.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#464 METAL-1404: Add annotation to enable CBO install via CVO in Hosted Clusters
  config/cluster-baremetal-operator/kustomization.yaml
  config/crd/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/proxyconfig.yaml
  config/prometheus/rbac.yaml
  config/prometheus/service.yaml
  config/rbac/kustomization.yaml
  config/webhook/kustomization.yaml
  controllers/bindata.go
  controllers/clusteroperator_test.go
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  manifests/0000_31_cluster-baremetal-operator_03_service.yaml
  manifests/0000_31_cluster-baremetal-operator_03_webhookservice.yaml
  manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
  manifests/0000_31_cluster-baremetal-operator_05_baremetal-kube-rbac-proxy-config.yaml
  manifests/0000_31_cluster-baremetal-operator_05_prometheus_rbac.yaml
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
  manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
Labels: lgtm, approved, jira/valid-reference

#491 Revert "METAL-1404: Add annotation to enable CBO install via CVO in Hosted Clusters"
  config/cluster-baremetal-operator/kustomization.yaml
  config/crd/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/proxyconfig.yaml
  config/prometheus/rbac.yaml
  config/prometheus/service.yaml
  config/rbac/kustomization.yaml
  config/webhook/kustomization.yaml
  controllers/bindata.go
  controllers/clusteroperator_test.go
  manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
  manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
  manifests/0000_31_cluster-baremetal-operator_03_service.yaml
  manifests/0000_31_cluster-baremetal-operator_03_webhookservice.yaml
  manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
  manifests/0000_31_cluster-baremetal-operator_05_baremetal-kube-rbac-proxy-config.yaml
  manifests/0000_31_cluster-baremetal-operator_05_prometheus_rbac.yaml
  manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
  manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
  manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
  manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
Labels: lgtm, approved, jira/valid-reference

#481 OCPBUGS-57419: Do not log "new CO status" unnecessarily
  controllers/clusteroperator.go
  controllers/clusteroperator_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference
