Repository openshift/cluster-baremetal-operator, pull requests merged in 2025-05, with the labels that each got.

#466 OCPBUGS-52483: Allow provisioningIP when network disabled
  api/v1alpha1/provisioning_validation.go
  api/v1alpha1/provisioning_validation_test.go
  go.mod
  go.sum
  provisioning/baremetal_config.go
  provisioning/baremetal_config_test.go
  provisioning/baremetal_pod_test.go
  vendor/github.com/go-errors/errors/.travis.yml
  vendor/github.com/go-errors/errors/README.md
  vendor/github.com/go-errors/errors/error.go
  vendor/github.com/go-errors/errors/error_1_13.go
  vendor/github.com/go-errors/errors/error_backward.go
  vendor/github.com/go-errors/errors/join_unwrap_1_20.go
  vendor/github.com/go-errors/errors/join_unwrap_backward.go
  vendor/github.com/go-errors/errors/stackframe.go
  vendor/modules.txt
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#477 NO-ISSUE: Silence a bogus error with newer golangci-lint
  provisioning/baremetal_config_test.go
Labels: lgtm, approved, jira/valid-reference

#475 NO-ISSUE: Makefile: don't run all linters when running unit tests
  Makefile
Labels: lgtm, approved, jira/valid-reference

#473 OCPBUGS-54965: Inform BMO when provisioning network is disabled
  provisioning/bmo_pod.go
  provisioning/bmo_pod_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
