Repository openshift/cluster-baremetal-operator, pull requests merged in 2025-08, with the labels that each got.

#496 OCPBUGS-53392: Remove webhookport (9447) as HostPort
  provisioning/bmo_pod.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#495 METAL-1508: Change deprecated pointer to ptr
  provisioning/baremetal_config.go
  provisioning/baremetal_pod.go
  provisioning/baremetal_webhook.go
  provisioning/bmo_pod.go
  provisioning/container_images.go
  provisioning/image_cache.go
  provisioning/image_customization.go
  provisioning/ironic_proxy.go
  provisioning/machine_os_images.go
  provisioning/webhook.go
Labels: lgtm, approved, jira/valid-reference

#492 OCPBUGS-58315: Bump github.com/go-errors/errors to v1.5.1
  go.mod
  go.sum
  vendor/github.com/go-errors/errors/.travis.yml
  vendor/github.com/go-errors/errors/README.md
  vendor/github.com/go-errors/errors/error.go
  vendor/github.com/go-errors/errors/error_1_13.go
  vendor/github.com/go-errors/errors/error_backward.go
  vendor/github.com/go-errors/errors/join_unwrap_1_20.go
  vendor/github.com/go-errors/errors/join_unwrap_backward.go
  vendor/github.com/go-errors/errors/stackframe.go
  vendor/modules.txt
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
